name: Deploy
on:
  push:
    branches:
      - wpl
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3
      - run: npm install
      # pathPrefix to match gh-pages default url https://<username>.github.io/<repo>
      - run: npm run build -- --pathPrefix="/wpl-stac-browser" --historyMode=hash
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages  # default: gh-pages
          exclude_assets: 'report.html'